---
slug: Cables_Pulleys_SolidWorks
filename: Cables_Pulleys_SolidWorks
title: Cables and Pulleys in SolidWorks
subtitle: A Brief Tutorial
description: A walk-through tutorial of 3D sketches and cable systems in SolidWorks.
author: Ben Smith
copyright: 2022
uuid: 4ac44a2f-e275-4f00-a8d7-0f60871310a9
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
